on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Actions of GitHub'
        run: pwd

      - name: 'Printing Name'
        run: echo 'Yosr Wael'

      - name: 'Printing File Content Before'
        run: ls

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Printing File Content After'
        run: ls

      - name: 'Login to Docker Hub'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 'Building Docker Hub image'
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/image1 .

      - name: 'Pushing image to Docker Hub'
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/image1


